// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SmartHome_Panel

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_LightScreen
void ui_LightScreen_screen_init(void);
lv_obj_t *ui_LightScreen;
lv_obj_t *ui_Header;
lv_obj_t *ui_LightDate;
lv_obj_t *ui_LightTime;
void ui_event_Light1Slider( lv_event_t * e);
lv_obj_t *ui_Light1Slider;
lv_obj_t *ui_Light1Lable;
void ui_event_Light1Switch( lv_event_t * e);
lv_obj_t *ui_Light1Switch;
void ui_event_Light2Slider( lv_event_t * e);
lv_obj_t *ui_Light2Slider;
lv_obj_t *ui_Light2Lable;
void ui_event_Light2Switch( lv_event_t * e);
lv_obj_t *ui_Light2Switch;
lv_obj_t *ui_Light3Lable;
void ui_event_Light3Switch( lv_event_t * e);
lv_obj_t *ui_Light3Switch;
void ui_event_Light3Slider( lv_event_t * e);
lv_obj_t *ui_Light3Slider;
void ui_event_Button1( lv_event_t * e);
lv_obj_t *ui_Button1;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Button2;
lv_obj_t *ui_Label4;


// SCREEN: ui_ThermostatScreen
void ui_ThermostatScreen_screen_init(void);
lv_obj_t *ui_ThermostatScreen;
lv_obj_t *ui_Header1;
lv_obj_t *ui_ThermoDate;
lv_obj_t *ui_ThermoTime;
lv_obj_t *ui_Button3;
lv_obj_t *ui_Label11;
void ui_event_Button4( lv_event_t * e);
lv_obj_t *ui_Button4;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Label8;
void ui_event_ACArc( lv_event_t * e);
lv_obj_t *ui_ACArc;
lv_obj_t *ui_Label10;
lv_obj_t *ui_TemperaturLable;
void ui_event_CelsiusButton( lv_event_t * e);
lv_obj_t *ui_CelsiusButton;
lv_obj_t *ui_Label14;
void ui_event_FahrenheitButton( lv_event_t * e);
lv_obj_t *ui_FahrenheitButton;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Label16;
lv_obj_t *ui_HumedityLable;
lv_obj_t *ui_ACValueLable;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Light1Slider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      Light_1_Slider_Changed( e );
}
}
void ui_event_Light1Switch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      Light_1_Button_Clicked( e );
}
}
void ui_event_Light2Slider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      Light_2_Slider_Changed( e );
}
}
void ui_event_Light2Switch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      Light_2_Button_Clicked( e );
}
}
void ui_event_Light3Switch( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      Light_3_Button_Clicked( e );
}
}
void ui_event_Light3Slider( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      Light_3_Slider_Changed( e );
}
}
void ui_event_Button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ThermostatScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ThermostatScreen_screen_init);
}
}
void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_LightScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_LightScreen_screen_init);
}
}
void ui_event_ACArc( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      UpdateAC( e );
}
}
void ui_event_CelsiusButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ToCelsius( e );
}
}
void ui_event_FahrenheitButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      ToFahrenheit( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_LightScreen_screen_init();
ui_ThermostatScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_LightScreen);
}
