// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SmartHome_Panel

#ifndef _SMARTHOME_PANEL_UI_H
#define _SMARTHOME_PANEL_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_LightScreen
void ui_LightScreen_screen_init(void);
extern lv_obj_t *ui_LightScreen;
extern lv_obj_t *ui_Header;
extern lv_obj_t *ui_LightDate;
extern lv_obj_t *ui_LightTime;
void ui_event_Light1Slider( lv_event_t * e);
extern lv_obj_t *ui_Light1Slider;
extern lv_obj_t *ui_Light1Lable;
void ui_event_Light1Switch( lv_event_t * e);
extern lv_obj_t *ui_Light1Switch;
void ui_event_Light2Slider( lv_event_t * e);
extern lv_obj_t *ui_Light2Slider;
extern lv_obj_t *ui_Light2Lable;
void ui_event_Light2Switch( lv_event_t * e);
extern lv_obj_t *ui_Light2Switch;
extern lv_obj_t *ui_Light3Lable;
void ui_event_Light3Switch( lv_event_t * e);
extern lv_obj_t *ui_Light3Switch;
void ui_event_Light3Slider( lv_event_t * e);
extern lv_obj_t *ui_Light3Slider;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label4;
// SCREEN: ui_ThermostatScreen
void ui_ThermostatScreen_screen_init(void);
extern lv_obj_t *ui_ThermostatScreen;
extern lv_obj_t *ui_Header1;
extern lv_obj_t *ui_ThermoDate;
extern lv_obj_t *ui_ThermoTime;
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label11;
void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_ACArc;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_TemperaturLable;
extern lv_obj_t *ui_CelsiusButton;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_FahrenheitButton;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_HumedityLable;
extern lv_obj_t *ui_ACValueLable;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
