// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_LightScreen
void ui_LightScreen_screen_init(void);
extern lv_obj_t *ui_LightScreen;
extern lv_obj_t *ui_Header;
extern lv_obj_t *ui_Date;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Slider1;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_Slider2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Switch2;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Switch3;
extern lv_obj_t *ui_Slider3;
void ui_event_Button1( lv_event_t * e);
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label4;
// SCREEN: ui_ThermostatScreen
void ui_ThermostatScreen_screen_init(void);
extern lv_obj_t *ui_ThermostatScreen;
extern lv_obj_t *ui_Header1;
extern lv_obj_t *ui_Date1;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_Button3;
extern lv_obj_t *ui_Label11;
void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
