// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SmartHome_Panel

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void Light_1_Slider_Changed(lv_event_t * e);
void Light_1_Button_Clicked(lv_event_t * e);
void Light_2_Slider_Changed(lv_event_t * e);
void Light_2_Button_Clicked(lv_event_t * e);
void Light_3_Button_Clicked(lv_event_t * e);
void Light_3_Slider_Changed(lv_event_t * e);
void UpdateAC(lv_event_t * e);
void ToCelsius(lv_event_t * e);
void ToFahrenheit(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
